//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace gloRemoteScanGeneral {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CardScanSettings.xsd")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/CardScanSettings.xsd", IsNullable=false)]
    public partial class CardScanSettings {
        
        private CardScanSettingsScanCardSettings[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScanCardSettings")]
        public CardScanSettingsScanCardSettings[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class CardScanSettingsScanCardSettings {
        
        private long scanCardSettingsIdField;
        
        private int insuranceCardDPIField;
        
        private int drivingLicenseCardDPIField;
        
        private string scannerColorField;
        
        private bool scanDuplexField;
        
        private bool centerImageField;
        
        private bool enableOCRField;
        
        private string cardTypeField;
        
        private string selectedScannerField;
        
        private string cardImageFrontField;
        
        private string cardFaceImageField;
        
        private string cardImageBackField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string dateOfBirthField;
        
        private string sexField;
        
        private string cityField;
        
        private string zipField;
        
        private string addressField;
        
        private string stateField;
        
        private string insMemberIDField;
        
        private string insMemberNameField;
        
        private string insGroupNoField;
        
        private string planProviderField;
        
        private string groupNumberField;
        
        private int statusField;
        
        private string descriptionField;
        
        public CardScanSettingsScanCardSettings() {
            this.insuranceCardDPIField = 600;
            this.drivingLicenseCardDPIField = 600;
            this.scanDuplexField = false;
            this.centerImageField = false;
            this.enableOCRField = false;
            this.statusField = -1;
        }
        
        /// <remarks/>
        public long ScanCardSettingsId {
            get {
                return this.scanCardSettingsIdField;
            }
            set {
                this.scanCardSettingsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(600)]
        public int InsuranceCardDPI {
            get {
                return this.insuranceCardDPIField;
            }
            set {
                this.insuranceCardDPIField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(600)]
        public int DrivingLicenseCardDPI {
            get {
                return this.drivingLicenseCardDPIField;
            }
            set {
                this.drivingLicenseCardDPIField = value;
            }
        }
        
        /// <remarks/>
        public string ScannerColor {
            get {
                return this.scannerColorField;
            }
            set {
                this.scannerColorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ScanDuplex {
            get {
                return this.scanDuplexField;
            }
            set {
                this.scanDuplexField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CenterImage {
            get {
                return this.centerImageField;
            }
            set {
                this.centerImageField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableOCR {
            get {
                return this.enableOCRField;
            }
            set {
                this.enableOCRField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SelectedScanner {
            get {
                return this.selectedScannerField;
            }
            set {
                this.selectedScannerField = value;
            }
        }
        
        /// <remarks/>
        public string CardImageFront {
            get {
                return this.cardImageFrontField;
            }
            set {
                this.cardImageFrontField = value;
            }
        }
        
        /// <remarks/>
        public string CardFaceImage {
            get {
                return this.cardFaceImageField;
            }
            set {
                this.cardFaceImageField = value;
            }
        }
        
        /// <remarks/>
        public string CardImageBack {
            get {
                return this.cardImageBackField;
            }
            set {
                this.cardImageBackField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string InsMemberID {
            get {
                return this.insMemberIDField;
            }
            set {
                this.insMemberIDField = value;
            }
        }
        
        /// <remarks/>
        public string InsMemberName {
            get {
                return this.insMemberNameField;
            }
            set {
                this.insMemberNameField = value;
            }
        }
        
        /// <remarks/>
        public string InsGroupNo {
            get {
                return this.insGroupNoField;
            }
            set {
                this.insGroupNoField = value;
            }
        }
        
        /// <remarks/>
        public string PlanProvider {
            get {
                return this.planProviderField;
            }
            set {
                this.planProviderField = value;
            }
        }
        
        /// <remarks/>
        public string GroupNumber {
            get {
                return this.groupNumberField;
            }
            set {
                this.groupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
}
