'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace svcEmail
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="svcEmail.IServiceEmail")>  _
    Public Interface IServiceEmail
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceEmail/SendEmail", ReplyAction:="http://tempuri.org/IServiceEmail/SendEmailResponse")>  _
        Function SendEmail(ByVal ToEmailAddress As String, ByVal Subject As String, ByVal Body As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceEmailChannel
        Inherits svcEmail.IServiceEmail, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceEmailClient
        Inherits System.ServiceModel.ClientBase(Of svcEmail.IServiceEmail)
        Implements svcEmail.IServiceEmail
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendEmail(ByVal ToEmailAddress As String, ByVal Subject As String, ByVal Body As String) As Boolean Implements svcEmail.IServiceEmail.SendEmail
            Return MyBase.Channel.SendEmail(ToEmailAddress, Subject, Body)
        End Function
    End Class
End Namespace
