'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Imports System.Xml.Serialization
Namespace WSInvitePrescriber
    '
    'This source code was auto-generated by xsd, Version=4.0.30319.1.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0"), _
     System.Xml.Serialization.XmlRootAttribute("EpcsRequest", [Namespace]:="urn:drfirst.com:epcsapi:v1_0", IsNullable:=False)> _
    Partial Public Class EpcsRequestType

        Private epcsRequestHeaderField As EpcsRequestHeaderType

        Private epcsRequestBodyField As EpcsRequestBodyType

        '''<remarks/>
        Public Property EpcsRequestHeader() As EpcsRequestHeaderType
            Get
                Return Me.epcsRequestHeaderField
            End Get
            Set(value As EpcsRequestHeaderType)
                Me.epcsRequestHeaderField = value
            End Set
        End Property
        <System.Xml.Serialization.XmlAttribute(AttributeName:="schemaLocation", [Namespace]:="http://www.w3.org/2001/XMLSchema-instance")> _
        Public Property schemaLocation() As String
            Get
                Return m_schemaLocation
            End Get
            Set(value As String)
                m_schemaLocation = value
            End Set
        End Property
        Private m_schemaLocation As String
        '''<remarks/>
        Public Property EpcsRequestBody() As EpcsRequestBodyType
            Get
                Return Me.epcsRequestBodyField
            End Get
            Set(value As EpcsRequestBodyType)
                Me.epcsRequestBodyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsRequestHeaderType

        Private vendorNameField As String

        Private vendorLabelField As String

        Private vendorNodeNameField As String

        Private vendorNodeLabelField As String

        Private appVersionField As AppVersionType

        Private sourceOrganizationIdField As String

        Private dateField As String

        '''<remarks/>
        Public Property VendorName() As String
            Get
                Return Me.vendorNameField
            End Get
            Set(value As String)
                Me.vendorNameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorLabel() As String
            Get
                Return Me.vendorLabelField
            End Get
            Set(value As String)
                Me.vendorLabelField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeName() As String
            Get
                Return Me.vendorNodeNameField
            End Get
            Set(value As String)
                Me.vendorNodeNameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeLabel() As String
            Get
                Return Me.vendorNodeLabelField
            End Get
            Set(value As String)
                Me.vendorNodeLabelField = value
            End Set
        End Property

        '''<remarks/>
        Public Property AppVersion() As AppVersionType
            Get
                Return Me.appVersionField
            End Get
            Set(value As AppVersionType)
                Me.appVersionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SourceOrganizationId() As String
            Get
                Return Me.sourceOrganizationIdField
            End Get
            Set(value As String)
                Me.sourceOrganizationIdField = value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As String
            Get
                Return Me.dateField
            End Get
            Set(value As String)
                Me.dateField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class AppVersionType

        Private appNameField As String

        Private applicationVersionField As String

        Private textField() As String

        '''<remarks/>
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set(value As String)
                Me.appNameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set(value As String)
                Me.applicationVersionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class PrescriberInviteRequestType

        Private npiField As Int64

        Private firstnameField As String

        Private lastnameField As String

        Private genderField As String

        Private primaryAddressline1Field As String

        Private primaryCityField As String

        Private primaryStateField As String

        Private primaryZipcodeField As String

        Private socialSecurityNumberField As String

        Private emailField As String

        Private dateofbirthField As String

        Private tokenMailingAddressline1Field As String

        Private tokenMailingAddressline2Field As String

        Private tokenMailingCityField As String

        Private tokenMailingStateField As String

        Private tokenMailingZipcodeField As String

        '''<remarks/>
        Public Property Npi() As Int64
            Get
                Return Me.npiField
            End Get
            Set(value As Int64)
                Me.npiField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set(value As String)
                Me.firstnameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set(value As String)
                Me.lastnameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set(value As String)
                Me.genderField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Dateofbirth() As String
            Get
                Return Me.dateofbirthField
            End Get
            Set(value As String)
                Me.dateofbirthField = value
            End Set
        End Property
        '''<remarks/>
        Public Property PrimaryAddressline1() As String
            Get
                Return Me.primaryAddressline1Field
            End Get
            Set(value As String)
                Me.primaryAddressline1Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryCity() As String
            Get
                Return Me.primaryCityField
            End Get
            Set(value As String)
                Me.primaryCityField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryState() As String
            Get
                Return Me.primaryStateField
            End Get
            Set(value As String)
                Me.primaryStateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryZipcode() As String
            Get
                Return Me.primaryZipcodeField
            End Get
            Set(value As String)
                Me.primaryZipcodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SocialSecurityNumber() As String
            Get
                Return Me.socialSecurityNumberField
            End Get
            Set(value As String)
                Me.socialSecurityNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set(value As String)
                Me.emailField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingAddressline1() As String
            Get
                Return Me.tokenMailingAddressline1Field
            End Get
            Set(value As String)
                Me.tokenMailingAddressline1Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingAddressline2() As String
            Get
                Return Me.tokenMailingAddressline2Field
            End Get
            Set(value As String)
                Me.tokenMailingAddressline2Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingCity() As String
            Get
                Return Me.tokenMailingCityField
            End Get
            Set(value As String)
                Me.tokenMailingCityField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingState() As String
            Get
                Return Me.tokenMailingStateField
            End Get
            Set(value As String)
                Me.tokenMailingStateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingZipcode() As String
            Get
                Return Me.tokenMailingZipcodeField
            End Get
            Set(value As String)
                Me.tokenMailingZipcodeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class PrescriberInviteRequestListType

        Private prescriberInviteRequestField As PrescriberInviteRequestType

        '''<remarks/>
        Public Property PrescriberInviteRequest() As PrescriberInviteRequestType
            Get
                Return Me.prescriberInviteRequestField
            End Get
            Set(value As PrescriberInviteRequestType)
                Me.prescriberInviteRequestField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class WsInvitePrescriberRequestType

        Private prescriberInviteRequestListField As PrescriberInviteRequestListType

        '''<remarks/>
        Public Property PrescriberInviteRequestList() As PrescriberInviteRequestListType
            Get
                Return Me.prescriberInviteRequestListField
            End Get
            Set(value As PrescriberInviteRequestListType)
                Me.prescriberInviteRequestListField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsRequestBodyType

        Private wsInvitePrescriberRequestField As WsInvitePrescriberRequestType

        '''<remarks/>
        Public Property WsInvitePrescriberRequest() As WsInvitePrescriberRequestType
            Get
                Return Me.wsInvitePrescriberRequestField
            End Get
            Set(value As WsInvitePrescriberRequestType)
                Me.wsInvitePrescriberRequestField = value
            End Set
        End Property
    End Class
End Namespace