//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace gloPatientSaving
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/SCRIPT")]
    [System.Xml.Serialization.XmlRootAttribute("OpportunityResponse", Namespace = "http://www.ncpdp.org/schema/SCRIPT", IsNullable = false)]
    public partial class OpportunityResponseType
    {

        private OpportunityPrescriber prescriberField;

        private OpportunityPatient patientField;

        private OpportunityBenefitsCoordination benefitsCoordinationField;

        private OpportunityDisposition opportunityDispositionField;

        /// <remarks/>
        public OpportunityPrescriber Prescriber
        {
            get
            {
                return this.prescriberField;
            }
            set
            {
                this.prescriberField = value;
            }
        }

        /// <remarks/>
        public OpportunityPatient Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }

        /// <remarks/>
        public OpportunityBenefitsCoordination BenefitsCoordination
        {
            get
            {
                return this.benefitsCoordinationField;
            }
            set
            {
                this.benefitsCoordinationField = value;
            }
        }

        /// <remarks/>
        public OpportunityDisposition OpportunityDisposition
        {
            get
            {
                return this.opportunityDispositionField;
            }
            set
            {
                this.opportunityDispositionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityPrescriber
    {

        private OpportunityProviderID identificationField;

        private NameType nameField;

        /// <remarks/>
        public OpportunityProviderID Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        /// <remarks/>
        public NameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class OpportunityProviderID
    {

        private string nPIField;

        /// <remarks/>
        public string NPI
        {
            get
            {
                return this.nPIField;
            }
            set
            {
                this.nPIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    [System.Xml.Serialization.XmlRootAttribute("Message", Namespace = "http://www.ncpdp.org/schema/Transport", IsNullable = false)]
    public partial class MessageType
    {

        private HeaderType headerField;

        private BodyType bodyField;

        private string datatypesVersionField;

        private string transportVersionField;

        private TransactionDomainVersionQualifierCode transactionDomainField;

        private string transactionVersionField;

        private string structuresVersionField;

        private string eCLVersionField;

        /// <remarks/>
        public HeaderType Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public BodyType Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatatypesVersion
        {
            get
            {
                return this.datatypesVersionField;
            }
            set
            {
                this.datatypesVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransportVersion
        {
            get
            {
                return this.transportVersionField;
            }
            set
            {
                this.transportVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransactionDomainVersionQualifierCode TransactionDomain
        {
            get
            {
                return this.transactionDomainField;
            }
            set
            {
                this.transactionDomainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionVersion
        {
            get
            {
                return this.transactionVersionField;
            }
            set
            {
                this.transactionVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructuresVersion
        {
            get
            {
                return this.structuresVersionField;
            }
            set
            {
                this.structuresVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ECLVersion
        {
            get
            {
                return this.eCLVersionField;
            }
            set
            {
                this.eCLVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class HeaderType
    {

        private QualifiedAddress toField;

        private QualifiedAddress fromField;

        private string messageIDField;

        private string relatesToMessageIDField;

        private System.DateTime sentTimeField;

        private SecurityType securityField;

        private SenderSoftwareType senderSoftwareField;

        private MailboxType mailboxField;

        private string testMessageField;

        private string rxReferenceNumberField;

        private string tertiaryIdentifierField;

        private string prescriberOrderNumberField;

        /// <remarks/>
        public QualifiedAddress To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        public QualifiedAddress From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        public string RelatesToMessageID
        {
            get
            {
                return this.relatesToMessageIDField;
            }
            set
            {
                this.relatesToMessageIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime SentTime
        {
            get
            {
                return this.sentTimeField;
            }
            set
            {
                this.sentTimeField = value;
            }
        }

        /// <remarks/>
        public SecurityType Security
        {
            get
            {
                return this.securityField;
            }
            set
            {
                this.securityField = value;
            }
        }

        /// <remarks/>
        public SenderSoftwareType SenderSoftware
        {
            get
            {
                return this.senderSoftwareField;
            }
            set
            {
                this.senderSoftwareField = value;
            }
        }

        /// <remarks/>
        public MailboxType Mailbox
        {
            get
            {
                return this.mailboxField;
            }
            set
            {
                this.mailboxField = value;
            }
        }

        /// <remarks/>
        public string TestMessage
        {
            get
            {
                return this.testMessageField;
            }
            set
            {
                this.testMessageField = value;
            }
        }

        /// <remarks/>
        public string RxReferenceNumber
        {
            get
            {
                return this.rxReferenceNumberField;
            }
            set
            {
                this.rxReferenceNumberField = value;
            }
        }

        /// <remarks/>
        public string TertiaryIdentifier
        {
            get
            {
                return this.tertiaryIdentifierField;
            }
            set
            {
                this.tertiaryIdentifierField = value;
            }
        }

        /// <remarks/>
        public string PrescriberOrderNumber
        {
            get
            {
                return this.prescriberOrderNumberField;
            }
            set
            {
                this.prescriberOrderNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class QualifiedAddress
    {

        private AddressTypeQualifier qualifierField;

        private bool qualifierFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AddressTypeQualifier Qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QualifierSpecified
        {
            get
            {
                return this.qualifierFieldSpecified;
            }
            set
            {
                this.qualifierFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum AddressTypeQualifier
    {

        /// <remarks/>
        P,

        /// <remarks/>
        C,

        /// <remarks/>
        M,

        /// <remarks/>
        D,

        /// <remarks/>
        ZZZ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class SecurityType
    {

        private UsernameTokenType usernameTokenField;

        private SecurityIdentificationType senderField;

        private SecurityIdentificationType receiverField;

        /// <remarks/>
        public UsernameTokenType UsernameToken
        {
            get
            {
                return this.usernameTokenField;
            }
            set
            {
                this.usernameTokenField = value;
            }
        }

        /// <remarks/>
        public SecurityIdentificationType Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        public SecurityIdentificationType Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class UsernameTokenType
    {

        private string usernameField;

        private PasswordType passwordField;

        private string nonceField;

        private System.DateTime createdField;

        private bool createdFieldSpecified;

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public PasswordType Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string Nonce
        {
            get
            {
                return this.nonceField;
            }
            set
            {
                this.nonceField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified
        {
            get
            {
                return this.createdFieldSpecified;
            }
            set
            {
                this.createdFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class PasswordType
    {

        private string typeField;

        private string valueField;

        public PasswordType()
        {
            this.typeField = "PasswordDigest";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class SecurityIdentificationType
    {

        private string secondaryIdentificationField;

        private string tertiaryIdentificationField;

        /// <remarks/>
        public string SecondaryIdentification
        {
            get
            {
                return this.secondaryIdentificationField;
            }
            set
            {
                this.secondaryIdentificationField = value;
            }
        }

        /// <remarks/>
        public string TertiaryIdentification
        {
            get
            {
                return this.tertiaryIdentificationField;
            }
            set
            {
                this.tertiaryIdentificationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class SenderSoftwareType
    {

        private string senderSoftwareDeveloperField;

        private string senderSoftwareProductField;

        private string senderSoftwareVersionReleaseField;

        /// <remarks/>
        public string SenderSoftwareDeveloper
        {
            get
            {
                return this.senderSoftwareDeveloperField;
            }
            set
            {
                this.senderSoftwareDeveloperField = value;
            }
        }

        /// <remarks/>
        public string SenderSoftwareProduct
        {
            get
            {
                return this.senderSoftwareProductField;
            }
            set
            {
                this.senderSoftwareProductField = value;
            }
        }

        /// <remarks/>
        public string SenderSoftwareVersionRelease
        {
            get
            {
                return this.senderSoftwareVersionReleaseField;
            }
            set
            {
                this.senderSoftwareVersionReleaseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class MailboxType
    {

        private string mailboxIDField;

        private string deliveredIDField;

        private string additionalTraceNumberField;

        private string acknowledgementIDField;

        /// <remarks/>
        public string MailboxID
        {
            get
            {
                return this.mailboxIDField;
            }
            set
            {
                this.mailboxIDField = value;
            }
        }

        /// <remarks/>
        public string DeliveredID
        {
            get
            {
                return this.deliveredIDField;
            }
            set
            {
                this.deliveredIDField = value;
            }
        }

        /// <remarks/>
        public string AdditionalTraceNumber
        {
            get
            {
                return this.additionalTraceNumberField;
            }
            set
            {
                this.additionalTraceNumberField = value;
            }
        }

        /// <remarks/>
        public string AcknowledgementID
        {
            get
            {
                return this.acknowledgementIDField;
            }
            set
            {
                this.acknowledgementIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class BodyType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(Error))]
        [System.Xml.Serialization.XmlElementAttribute("OpportunityNotification", typeof(OpportunityNotificationType))]
        [System.Xml.Serialization.XmlElementAttribute("OpportunityResponse", typeof(OpportunityResponseType))]
        [System.Xml.Serialization.XmlElementAttribute("PatientSavingsNotification", typeof(PatientSavingsNotificationType))]
        [System.Xml.Serialization.XmlElementAttribute("Status", typeof(Status))]
        [System.Xml.Serialization.XmlElementAttribute("Verify", typeof(Verify))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class Error
    {

        private TransactionErrorCode codeField;

        private DescriptionCode[] descriptionCodeField;

        private string descriptionField;

        /// <remarks/>
        public TransactionErrorCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptionCode")]
        public DescriptionCode[] DescriptionCode
        {
            get
            {
                return this.descriptionCodeField;
            }
            set
            {
                this.descriptionCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum TransactionErrorCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("600")]
        Item600,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("601")]
        Item601,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("602")]
        Item602,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("900")]
        Item900,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum DescriptionCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")]
        Item500,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1000")]
        Item1000,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2000")]
        Item2000,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3000")]
        Item3000,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/SCRIPT")]
    [System.Xml.Serialization.XmlRootAttribute("OpportunityNotification", Namespace = "http://www.ncpdp.org/schema/SCRIPT", IsNullable = false)]
    public partial class OpportunityNotificationType
    {

        private OpportunityPrescriber prescriberField;

        private OpportunityPatient patientField;

        private OpportunityBenefitsCoordination benefitsCoordinationField;

        private OpportunityType[] opportunityField;

        /// <remarks/>
        public OpportunityPrescriber Prescriber
        {
            get
            {
                return this.prescriberField;
            }
            set
            {
                this.prescriberField = value;
            }
        }

        /// <remarks/>
        public OpportunityPatient Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }

        /// <remarks/>
        public OpportunityBenefitsCoordination BenefitsCoordination
        {
            get
            {
                return this.benefitsCoordinationField;
            }
            set
            {
                this.benefitsCoordinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Opportunity")]
        public OpportunityType[] Opportunity
        {
            get
            {
                return this.opportunityField;
            }
            set
            {
                this.opportunityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityPatient
    {

        private OpportunityPatientID identificationField;

        private NameType nameField;

        private GenderCode genderField;

        private DateType dateOfBirthField;

        private MandatoryAddressType addressField;

        private CommunicationNumbersType communicationNumbersField;

        /// <remarks/>
        public OpportunityPatientID Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        /// <remarks/>
        public NameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public GenderCode Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        public DateType DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        public MandatoryAddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public CommunicationNumbersType CommunicationNumbers
        {
            get
            {
                return this.communicationNumbersField;
            }
            set
            {
                this.communicationNumbersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class OpportunityPatientID
    {

        private string medicalRecordIdentificationNumberEHRField;

        /// <remarks/>
        public string MedicalRecordIdentificationNumberEHR
        {
            get
            {
                return this.medicalRecordIdentificationNumberEHRField;
            }
            set
            {
                this.medicalRecordIdentificationNumberEHRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class NameType
    {

        private string lastNameField;

        private string firstNameField;

        private string middleNameField;

        private string suffixField;

        private string prefixField;

        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        public string Suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }

        /// <remarks/>
        public string Prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum GenderCode
    {

        /// <remarks/>
        M,

        /// <remarks/>
        F,

        /// <remarks/>
        U,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class DateType
    {

        private System.DateTime itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        Date,

        /// <remarks/>
        DateTime,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class MandatoryAddressType : AddressType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MandatoryAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class AddressType
    {

        private string addressLine1Field;

        private string addressLine2Field;

        private string cityField;

        private StateCode stateField;

        private bool stateFieldSpecified;

        private string zipCodeField;

        /// <remarks/>
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public StateCode State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified
        {
            get
            {
                return this.stateFieldSpecified;
            }
            set
            {
                this.stateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum StateCode
    {

        /// <remarks/>
        WA,

        /// <remarks/>
        OK,

        /// <remarks/>
        AZ,

        /// <remarks/>
        ON,

        /// <remarks/>
        HI,

        /// <remarks/>
        MO,

        /// <remarks/>
        NU,

        /// <remarks/>
        VI,

        /// <remarks/>
        AK,

        /// <remarks/>
        TX,

        /// <remarks/>
        OH,

        /// <remarks/>
        GU,

        /// <remarks/>
        MS,

        /// <remarks/>
        MP,

        /// <remarks/>
        AL,

        /// <remarks/>
        VA,

        /// <remarks/>
        NT,

        /// <remarks/>
        GA,

        /// <remarks/>
        TN,

        /// <remarks/>
        ND,

        /// <remarks/>
        MN,

        /// <remarks/>
        NS,

        /// <remarks/>
        FM,

        /// <remarks/>
        SD,

        /// <remarks/>
        FL,

        /// <remarks/>
        NL,

        /// <remarks/>
        DC,

        /// <remarks/>
        MI,

        /// <remarks/>
        NB,

        /// <remarks/>
        NC,

        /// <remarks/>
        SC,

        /// <remarks/>
        MA,

        /// <remarks/>
        DE,

        /// <remarks/>
        MB,

        /// <remarks/>
        RI,

        /// <remarks/>
        NY,

        /// <remarks/>
        BC,

        /// <remarks/>
        CT,

        /// <remarks/>
        MD,

        /// <remarks/>
        PR,

        /// <remarks/>
        NM,

        /// <remarks/>
        ME,

        /// <remarks/>
        AB,

        /// <remarks/>
        LA,

        /// <remarks/>
        MH,

        /// <remarks/>
        KS,

        /// <remarks/>
        CO,

        /// <remarks/>
        NV,

        /// <remarks/>
        NJ,

        /// <remarks/>
        PA,

        /// <remarks/>
        YT,

        /// <remarks/>
        KY,

        /// <remarks/>
        CA,

        /// <remarks/>
        AS,

        /// <remarks/>
        WY,

        /// <remarks/>
        IA,

        /// <remarks/>
        NH,

        /// <remarks/>
        NE,

        /// <remarks/>
        PW,

        /// <remarks/>
        SK,

        /// <remarks/>
        IN,

        /// <remarks/>
        AR,

        /// <remarks/>
        WI,

        /// <remarks/>
        IL,

        /// <remarks/>
        QC,

        /// <remarks/>
        VT,

        /// <remarks/>
        OR,

        /// <remarks/>
        WV,

        /// <remarks/>
        PE,

        /// <remarks/>
        MT,

        /// <remarks/>
        ID,

        /// <remarks/>
        UT,

        /// <remarks/>
        AA,

        /// <remarks/>
        AE,

        /// <remarks/>
        AP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class CommunicationNumbersType
    {

        private PhoneType primaryTelephoneField;

        /// <remarks/>
        public PhoneType PrimaryTelephone
        {
            get
            {
                return this.primaryTelephoneField;
            }
            set
            {
                this.primaryTelephoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class PhoneType
    {

        private string numberField;

        private string extensionField;

        private BooleanCode supportsSMSField;

        private bool supportsSMSFieldSpecified;

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        public BooleanCode SupportsSMS
        {
            get
            {
                return this.supportsSMSField;
            }
            set
            {
                this.supportsSMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsSMSSpecified
        {
            get
            {
                return this.supportsSMSFieldSpecified;
            }
            set
            {
                this.supportsSMSFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum BooleanCode
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityBenefitsCoordination
    {

        private string pBMMemberIDField;

        /// <remarks/>
        public string PBMMemberID
        {
            get
            {
                return this.pBMMemberIDField;
            }
            set
            {
                this.pBMMemberIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PatientSavingsOpportunityType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityType
    {

        private string opportunityIDField;

        private string opportunityType1Field;

        /// <remarks/>
        public string OpportunityID
        {
            get
            {
                return this.opportunityIDField;
            }
            set
            {
                this.opportunityIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpportunityType")]
        public string OpportunityType1
        {
            get
            {
                return this.opportunityType1Field;
            }
            set
            {
                this.opportunityType1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class PatientSavingsOpportunityType : OpportunityType
    {

        private string opportunityHeadlineField;

        private string opportunityBodyField;

        private string annualCostSavingsField;

        private OpportunityOriginalPrescription originalPrescriptionField;

        private OpportunityAlternativeMedication[] alternativeMedicationField;

        /// <remarks/>
        public string OpportunityHeadline
        {
            get
            {
                return this.opportunityHeadlineField;
            }
            set
            {
                this.opportunityHeadlineField = value;
            }
        }

        /// <remarks/>
        public string OpportunityBody
        {
            get
            {
                return this.opportunityBodyField;
            }
            set
            {
                this.opportunityBodyField = value;
            }
        }

        /// <remarks/>
        public string AnnualCostSavings
        {
            get
            {
                return this.annualCostSavingsField;
            }
            set
            {
                this.annualCostSavingsField = value;
            }
        }

        /// <remarks/>
        public OpportunityOriginalPrescription OriginalPrescription
        {
            get
            {
                return this.originalPrescriptionField;
            }
            set
            {
                this.originalPrescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternativeMedication")]
        public OpportunityAlternativeMedication[] AlternativeMedication
        {
            get
            {
                return this.alternativeMedicationField;
            }
            set
            {
                this.alternativeMedicationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityOriginalPrescription
    {

        private string drugDescriptionField;

        private OpportunityDrugCoded drugCodedField;

        private OpportunityQuantity quantityField;

        private string daysSupplyField;

        private DateType writtenDateField;

        private DateType lastFillDateField;

        private OpportunityOriginalPharmacy pharmacyField;

        private OpportunityPrescriber prescriberField;

        /// <remarks/>
        public string DrugDescription
        {
            get
            {
                return this.drugDescriptionField;
            }
            set
            {
                this.drugDescriptionField = value;
            }
        }

        /// <remarks/>
        public OpportunityDrugCoded DrugCoded
        {
            get
            {
                return this.drugCodedField;
            }
            set
            {
                this.drugCodedField = value;
            }
        }

        /// <remarks/>
        public OpportunityQuantity Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string DaysSupply
        {
            get
            {
                return this.daysSupplyField;
            }
            set
            {
                this.daysSupplyField = value;
            }
        }

        /// <remarks/>
        public DateType WrittenDate
        {
            get
            {
                return this.writtenDateField;
            }
            set
            {
                this.writtenDateField = value;
            }
        }

        /// <remarks/>
        public DateType LastFillDate
        {
            get
            {
                return this.lastFillDateField;
            }
            set
            {
                this.lastFillDateField = value;
            }
        }

        /// <remarks/>
        public OpportunityOriginalPharmacy Pharmacy
        {
            get
            {
                return this.pharmacyField;
            }
            set
            {
                this.pharmacyField = value;
            }
        }

        /// <remarks/>
        public OpportunityPrescriber Prescriber
        {
            get
            {
                return this.prescriberField;
            }
            set
            {
                this.prescriberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class OpportunityDrugCoded
    {

        private QualifiedCode[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DrugDBCode", typeof(DrugDBCode))]
        [System.Xml.Serialization.XmlElementAttribute("ProductCode", typeof(ProductCode))]
        public QualifiedCode[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class DrugDBCode : QualifiedCode
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrugDBCode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class QualifiedCode
    {

        private string codeField;

        private string qualifierField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class ProductCode : QualifiedCode
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class OpportunityQuantity
    {

        private string valueField;

        private QuantityCodeListQualifierCode codeListQualifierField;

        private bool codeListQualifierFieldSpecified;

        private NCICode quantityUnitOfMeasureField;

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public QuantityCodeListQualifierCode CodeListQualifier
        {
            get
            {
                return this.codeListQualifierField;
            }
            set
            {
                this.codeListQualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeListQualifierSpecified
        {
            get
            {
                return this.codeListQualifierFieldSpecified;
            }
            set
            {
                this.codeListQualifierFieldSpecified = value;
            }
        }

        /// <remarks/>
        public NCICode QuantityUnitOfMeasure
        {
            get
            {
                return this.quantityUnitOfMeasureField;
            }
            set
            {
                this.quantityUnitOfMeasureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum QuantityCodeListQualifierCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("87")]
        Item87,

        /// <remarks/>
        QS,

        /// <remarks/>
        CF,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class NCICode
    {

        private string codeField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityOriginalPharmacy
    {

        private OpportunityPharmacyID identificationField;

        private string businessNameField;

        private AddressType addressField;

        private CommunicationNumbersType communicationNumbersField;

        /// <remarks/>
        public OpportunityPharmacyID Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        /// <remarks/>
        public string BusinessName
        {
            get
            {
                return this.businessNameField;
            }
            set
            {
                this.businessNameField = value;
            }
        }

        /// <remarks/>
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public CommunicationNumbersType CommunicationNumbers
        {
            get
            {
                return this.communicationNumbersField;
            }
            set
            {
                this.communicationNumbersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/datatypes")]
    public partial class OpportunityPharmacyID
    {

        private string nCPDPIDField;

        private object nPIField;

        /// <remarks/>
        public string NCPDPID
        {
            get
            {
                return this.nCPDPIDField;
            }
            set
            {
                this.nCPDPIDField = value;
            }
        }

        /// <remarks/>
        public object NPI
        {
            get
            {
                return this.nPIField;
            }
            set
            {
                this.nPIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityAlternativeMedication
    {

        private string drugDescriptionField;

        private OpportunityDrugCoded drugCodedField;



        public string DrugDescription
        {
            get
            {
                return this.drugDescriptionField;
            }
            set
            {
                this.drugDescriptionField = value;
            }
        }

        /// <remarks/>
        public OpportunityDrugCoded DrugCoded
        {
            get
            {
                return this.drugCodedField;
            }
            set
            {
                this.drugCodedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/SCRIPT")]
    [System.Xml.Serialization.XmlRootAttribute("PatientSavingsNotification", Namespace = "http://www.ncpdp.org/schema/SCRIPT", IsNullable = false)]
    public partial class PatientSavingsNotificationType
    {

        private OpportunityPrescriber prescriberField;

        private OpportunityPatient patientField;

        private OpportunityBenefitsCoordination benefitsCoordinationField;

        private PatientSavingsOpportunityType[] opportunityField;

        /// <remarks/>
        public OpportunityPrescriber Prescriber
        {
            get
            {
                return this.prescriberField;
            }
            set
            {
                this.prescriberField = value;
            }
        }

        /// <remarks/>
        public OpportunityPatient Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }

        /// <remarks/>
        public OpportunityBenefitsCoordination BenefitsCoordination
        {
            get
            {
                return this.benefitsCoordinationField;
            }
            set
            {
                this.benefitsCoordinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Opportunity")]
        public PatientSavingsOpportunityType[] Opportunity
        {
            get
            {
                return this.opportunityField;
            }
            set
            {
                this.opportunityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class Status
    {

        private StatusCode codeField;

        private DescriptionCode[] descriptionCodeField;

        private string descriptionField;

        private PrescriptionDeliveryMethod prescriptionDeliveryMethodField;

        private bool prescriptionDeliveryMethodFieldSpecified;

        /// <remarks/>
        public StatusCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptionCode")]
        public DescriptionCode[] DescriptionCode
        {
            get
            {
                return this.descriptionCodeField;
            }
            set
            {
                this.descriptionCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public PrescriptionDeliveryMethod PrescriptionDeliveryMethod
        {
            get
            {
                return this.prescriptionDeliveryMethodField;
            }
            set
            {
                this.prescriptionDeliveryMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrescriptionDeliveryMethodSpecified
        {
            get
            {
                return this.prescriptionDeliveryMethodFieldSpecified;
            }
            set
            {
                this.prescriptionDeliveryMethodFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum StatusCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("000")]
        Item000,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum PrescriptionDeliveryMethod
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class Verify
    {

        private VerifyVerifyStatus verifyStatusField;

        /// <remarks/>
        public VerifyVerifyStatus VerifyStatus
        {
            get
            {
                return this.verifyStatusField;
            }
            set
            {
                this.verifyStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ncpdp.org/schema/Transport")]
    public partial class VerifyVerifyStatus
    {

        private string codeField;

        private string descriptionField;

        private PrescriptionDeliveryMethod prescriptionDeliveryMethodField;

        private bool prescriptionDeliveryMethodFieldSpecified;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public PrescriptionDeliveryMethod PrescriptionDeliveryMethod
        {
            get
            {
                return this.prescriptionDeliveryMethodField;
            }
            set
            {
                this.prescriptionDeliveryMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrescriptionDeliveryMethodSpecified
        {
            get
            {
                return this.prescriptionDeliveryMethodFieldSpecified;
            }
            set
            {
                this.prescriptionDeliveryMethodFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/ecl")]
    public enum TransactionDomainVersionQualifierCode
    {

        /// <remarks/>
        SCRIPT,

        /// <remarks/>
        Specialized,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ncpdp.org/schema/structures")]
    public partial class OpportunityDisposition
    {

        private string opportunityIDField;

        private string opportunityTypeField;

        private DateType dispositionDateField;

        private string dispositionCodeField;

        /// <remarks/>
        public string OpportunityID
        {
            get
            {
                return this.opportunityIDField;
            }
            set
            {
                this.opportunityIDField = value;
            }
        }

        /// <remarks/>
        public string OpportunityType
        {
            get
            {
                return this.opportunityTypeField;
            }
            set
            {
                this.opportunityTypeField = value;
            }
        }

        /// <remarks/>
        public DateType DispositionDate
        {
            get
            {
                return this.dispositionDateField;
            }
            set
            {
                this.dispositionDateField = value;
            }
        }

        /// <remarks/>
        public string DispositionCode
        {
            get
            {
                return this.dispositionCodeField;
            }
            set
            {
                this.dispositionCodeField = value;
            }
        }
    }
}