'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("gloEmdeonCommon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property CPT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CPT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CPT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CPT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Custom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Custom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Down24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Down24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DownHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flag_Yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag_Yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ICD_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICD_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ICD10GalleryGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICD10GalleryGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_Blue2007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_Blue2007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_LongButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_LongButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_LongOrange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_LongOrange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_LongYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_LongYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Img_Toolstrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_Toolstrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Modify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Modify1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modify1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallDown_Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallDown_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallLeft_Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallLeft_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallRight_Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallRight_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallUp_Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallUp_Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Up24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Up24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UPHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UPHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YellowDown24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowDown24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YellowUp24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowUp24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
