'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

Namespace SS_Resp_WSInvitePrescriber
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0", IsNullable:=False)> _
    Partial Public Class EpcsResponse

        Private epcsResponseHeaderField As EpcsResponseEpcsResponseHeader

        Private epcsRequestField As EpcsResponseEpcsRequest

        Private epcsResponseBodyField As EpcsResponseEpcsResponseBody

        '''<remarks/>
        Public Property EpcsResponseHeader() As EpcsResponseEpcsResponseHeader
            Get
                Return Me.epcsResponseHeaderField
            End Get
            Set(value As EpcsResponseEpcsResponseHeader)
                Me.epcsResponseHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsRequest() As EpcsResponseEpcsRequest
            Get
                Return Me.epcsRequestField
            End Get
            Set(value As EpcsResponseEpcsRequest)
                Me.epcsRequestField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsResponseBody() As EpcsResponseEpcsResponseBody
            Get
                Return Me.epcsResponseBodyField
            End Get
            Set(value As EpcsResponseEpcsResponseBody)
                Me.epcsResponseBodyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseHeader

        Private serverNameField As String

        Private epcsApiVersionField As String

        Private serverVersionField As EpcsResponseEpcsResponseHeaderServerVersion

        Private dateField As Date

        '''<remarks/>
        Public Property ServerName() As String
            Get
                Return Me.serverNameField
            End Get
            Set(value As String)
                Me.serverNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsApiVersion() As String
            Get
                Return Me.epcsApiVersionField
            End Get
            Set(value As String)
                Me.epcsApiVersionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ServerVersion() As EpcsResponseEpcsResponseHeaderServerVersion
            Get
                Return Me.serverVersionField
            End Get
            Set(value As EpcsResponseEpcsResponseHeaderServerVersion)
                Me.serverVersionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set(value As Date)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseHeaderServerVersion

        Private appNameField As String

        Private applicationVersionField As String

        '''<remarks/>
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set(value As String)
                Me.appNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set(value As String)
                Me.applicationVersionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequest

        Private epcsRequestHeaderField As EpcsResponseEpcsRequestEpcsRequestHeader

        Private epcsRequestBodyField As EpcsResponseEpcsRequestEpcsRequestBody

        '''<remarks/>
        Public Property EpcsRequestHeader() As EpcsResponseEpcsRequestEpcsRequestHeader
            Get
                Return Me.epcsRequestHeaderField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestHeader)
                Me.epcsRequestHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsRequestBody() As EpcsResponseEpcsRequestEpcsRequestBody
            Get
                Return Me.epcsRequestBodyField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBody)
                Me.epcsRequestBodyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestHeader

        Private vendorNameField As String

        Private vendorLabelField As String

        Private vendorNodeNameField As String

        Private vendorNodeLabelField As String

        Private appVersionField As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion

        Private sourceOrganizationIdField As String

        Private dateField As String

        '''<remarks/>
        Public Property VendorName() As String
            Get
                Return Me.vendorNameField
            End Get
            Set(value As String)
                Me.vendorNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorLabel() As String
            Get
                Return Me.vendorLabelField
            End Get
            Set(value As String)
                Me.vendorLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeName() As String
            Get
                Return Me.vendorNodeNameField
            End Get
            Set(value As String)
                Me.vendorNodeNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeLabel() As String
            Get
                Return Me.vendorNodeLabelField
            End Get
            Set(value As String)
                Me.vendorNodeLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AppVersion() As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion
            Get
                Return Me.appVersionField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion)
                Me.appVersionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SourceOrganizationId() As String
            Get
                Return Me.sourceOrganizationIdField
            End Get
            Set(value As String)
                Me.sourceOrganizationIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As String
            Get
                Return Me.dateField
            End Get
            Set(value As String)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion

        Private appNameField As String

        Private applicationVersionField As String

        '''<remarks/>
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set(value As String)
                Me.appNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set(value As String)
                Me.applicationVersionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBody

        Private wsInvitePrescriberRequestField As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequest

        '''<remarks/>
        Public Property WsInvitePrescriberRequest() As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequest
            Get
                Return Me.wsInvitePrescriberRequestField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequest)
                Me.wsInvitePrescriberRequestField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequest

        Private prescriberInviteRequestListField As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestList

        '''<remarks/>
        Public Property PrescriberInviteRequestList() As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestList
            Get
                Return Me.prescriberInviteRequestListField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestList)
                Me.prescriberInviteRequestListField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestList

        Private prescriberInviteRequestField As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestListPrescriberInviteRequest

        '''<remarks/>
        Public Property PrescriberInviteRequest() As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestListPrescriberInviteRequest
            Get
                Return Me.prescriberInviteRequestField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestListPrescriberInviteRequest)
                Me.prescriberInviteRequestField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBodyWsInvitePrescriberRequestPrescriberInviteRequestListPrescriberInviteRequest

        Private npiField As Int64

        Private firstnameField As String

        Private lastnameField As String

        Private genderField As String

        Private primaryAddressline1Field As String

        Private primaryCityField As String

        Private primaryZipcodeField As String

        Private socialSecurityNumberField As String

        Private emailField As String

        Private tokenMailingAddressline1Field As String

        Private tokenMailingAddressline2Field As String

        Private tokenMailingCityField As String

        Private tokenMailingZipcodeField As String

        '''<remarks/>
        Public Property Npi() As Int64
            Get
                Return Me.npiField
            End Get
            Set(value As Int64)
                Me.npiField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set(value As String)
                Me.firstnameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set(value As String)
                Me.lastnameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set(value As String)
                Me.genderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryAddressline1() As String
            Get
                Return Me.primaryAddressline1Field
            End Get
            Set(value As String)
                Me.primaryAddressline1Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryCity() As String
            Get
                Return Me.primaryCityField
            End Get
            Set(value As String)
                Me.primaryCityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PrimaryZipcode() As String
            Get
                Return Me.primaryZipcodeField
            End Get
            Set(value As String)
                Me.primaryZipcodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SocialSecurityNumber() As String
            Get
                Return Me.socialSecurityNumberField
            End Get
            Set(value As String)
                Me.socialSecurityNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set(value As String)
                Me.emailField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingAddressline1() As String
            Get
                Return Me.tokenMailingAddressline1Field
            End Get
            Set(value As String)
                Me.tokenMailingAddressline1Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingAddressline2() As String
            Get
                Return Me.tokenMailingAddressline2Field
            End Get
            Set(value As String)
                Me.tokenMailingAddressline2Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingCity() As String
            Get
                Return Me.tokenMailingCityField
            End Get
            Set(value As String)
                Me.tokenMailingCityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TokenMailingZipcode() As String
            Get
                Return Me.tokenMailingZipcodeField
            End Get
            Set(value As String)
                Me.tokenMailingZipcodeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBody

        Private wsInvitePrescriberResponseField As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponse

        Private errorResponseField As EpcsResponseEpcsResponseBodyErrorResponse

        '''<remarks/>
        Public Property WsInvitePrescriberResponse() As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponse
            Get
                Return Me.wsInvitePrescriberResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponse)
                Me.wsInvitePrescriberResponseField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorResponse() As EpcsResponseEpcsResponseBodyErrorResponse
            Get
                Return Me.errorResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponse)
                Me.errorResponseField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsInvitePrescriberResponse

        Private prescriberStatusResponseListField As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseList

        '''<remarks/>
        Public Property PrescriberStatusResponseList() As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseList
            Get
                Return Me.prescriberStatusResponseListField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseList)
                Me.prescriberStatusResponseListField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseList

        Private prescriberStatusResponseField As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponse

        '''<remarks/>
        Public Property PrescriberStatusResponse() As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponse
            Get
                Return Me.prescriberStatusResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponse)
                Me.prescriberStatusResponseField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponse

        Private npiField As Int64

        Private statusField As String

        Private errorField As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponseError

        '''<remarks/>
        Public Property Npi() As Int64
            Get
                Return Me.npiField
            End Get
            Set(value As Int64)
                Me.npiField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set(value As String)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Error]() As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponseError
            Get
                Return Me.errorField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponseError)
                Me.errorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsInvitePrescriberResponsePrescriberStatusResponseListPrescriberStatusResponseError

        Private errorCodeField As String

        Private errorTextField As String

        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set(value As String)
                Me.errorCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorText() As String
            Get
                Return Me.errorTextField
            End Get
            Set(value As String)
                Me.errorTextField = Value
            End Set
        End Property
    End Class
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponse

        Private errorResponseListField As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList

        '''<remarks/>
        Public Property ErrorResponseList() As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList
            Get
                Return Me.errorResponseListField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList)
                Me.errorResponseListField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList

        Private errorField As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError

        '''<remarks/>
        Public Property [Error]() As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError
            Get
                Return Me.errorField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError)
                Me.errorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError

        Private errorCodeField As String

        Private errorTextField As String

        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set(value As String)
                Me.errorCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorText() As String
            Get
                Return Me.errorTextField
            End Get
            Set(value As String)
                Me.errorTextField = value
            End Set
        End Property
    End Class
End Namespace