'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace SS_Resp_WSSetUpOrganization
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="urn:drfirst.com:epcsapi:v1_0", IsNullable:=False)> _
    Partial Public Class EpcsResponse

        Private epcsResponseHeaderField As EpcsResponseEpcsResponseHeader

        Private epcsRequestField As EpcsResponseEpcsRequest

        Private epcsResponseBodyField As EpcsResponseEpcsResponseBody

        '''<remarks/>
        Public Property EpcsResponseHeader() As EpcsResponseEpcsResponseHeader
            Get
                Return Me.epcsResponseHeaderField
            End Get
            Set(value As EpcsResponseEpcsResponseHeader)
                Me.epcsResponseHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsRequest() As EpcsResponseEpcsRequest
            Get
                Return Me.epcsRequestField
            End Get
            Set(value As EpcsResponseEpcsRequest)
                Me.epcsRequestField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsResponseBody() As EpcsResponseEpcsResponseBody
            Get
                Return Me.epcsResponseBodyField
            End Get
            Set(value As EpcsResponseEpcsResponseBody)
                Me.epcsResponseBodyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseHeader

        Private serverNameField As String

        Private epcsApiVersionField As String

        Private serverVersionField As EpcsResponseEpcsResponseHeaderServerVersion

        Private dateField As Date

        '''<remarks/>
        Public Property ServerName() As String
            Get
                Return Me.serverNameField
            End Get
            Set(value As String)
                Me.serverNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsApiVersion() As String
            Get
                Return Me.epcsApiVersionField
            End Get
            Set(value As String)
                Me.epcsApiVersionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ServerVersion() As EpcsResponseEpcsResponseHeaderServerVersion
            Get
                Return Me.serverVersionField
            End Get
            Set(value As EpcsResponseEpcsResponseHeaderServerVersion)
                Me.serverVersionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set(value As Date)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseHeaderServerVersion

        Private appNameField As String

        Private applicationVersionField As String

        '''<remarks/>
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set(value As String)
                Me.appNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set(value As String)
                Me.applicationVersionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequest

        Private epcsRequestHeaderField As EpcsResponseEpcsRequestEpcsRequestHeader

        Private epcsRequestBodyField As EpcsResponseEpcsRequestEpcsRequestBody

        '''<remarks/>
        Public Property EpcsRequestHeader() As EpcsResponseEpcsRequestEpcsRequestHeader
            Get
                Return Me.epcsRequestHeaderField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestHeader)
                Me.epcsRequestHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EpcsRequestBody() As EpcsResponseEpcsRequestEpcsRequestBody
            Get
                Return Me.epcsRequestBodyField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBody)
                Me.epcsRequestBodyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestHeader

        Private vendorNameField As String

        Private vendorLabelField As String

        Private vendorNodeNameField As String

        Private vendorNodeLabelField As String

        Private appVersionField As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion

        Private sourceOrganizationIdField As String

        Private dateField As String

        '''<remarks/>
        Public Property VendorName() As String
            Get
                Return Me.vendorNameField
            End Get
            Set(value As String)
                Me.vendorNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorLabel() As String
            Get
                Return Me.vendorLabelField
            End Get
            Set(value As String)
                Me.vendorLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeName() As String
            Get
                Return Me.vendorNodeNameField
            End Get
            Set(value As String)
                Me.vendorNodeNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeLabel() As String
            Get
                Return Me.vendorNodeLabelField
            End Get
            Set(value As String)
                Me.vendorNodeLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AppVersion() As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion
            Get
                Return Me.appVersionField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion)
                Me.appVersionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SourceOrganizationId() As String
            Get
                Return Me.sourceOrganizationIdField
            End Get
            Set(value As String)
                Me.sourceOrganizationIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As String
            Get
                Return Me.dateField
            End Get
            Set(value As String)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestHeaderAppVersion

        Private appNameField As String

        Private applicationVersionField As String

        '''<remarks/>
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set(value As String)
                Me.appNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set(value As String)
                Me.applicationVersionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBody

        Private wsSetUpOrganizationStatusRequestField As EpcsResponseEpcsRequestEpcsRequestBodyWsSetUpOrganizationStatusRequest

        '''<remarks/>
        Public Property WsSetUpOrganizationStatusRequest() As EpcsResponseEpcsRequestEpcsRequestBodyWsSetUpOrganizationStatusRequest
            Get
                Return Me.wsSetUpOrganizationStatusRequestField
            End Get
            Set(value As EpcsResponseEpcsRequestEpcsRequestBodyWsSetUpOrganizationStatusRequest)
                Me.wsSetUpOrganizationStatusRequestField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsRequestEpcsRequestBodyWsSetUpOrganizationStatusRequest

        Private vendorLabelField As String

        Private vendorNodeLabelField As String

        Private organizationNameField As String

        Private organizationLabelField As String

        '''<remarks/>
        Public Property VendorLabel() As String
            Get
                Return Me.vendorLabelField
            End Get
            Set(value As String)
                Me.vendorLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorNodeLabel() As String
            Get
                Return Me.vendorNodeLabelField
            End Get
            Set(value As String)
                Me.vendorNodeLabelField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OrganizationName() As String
            Get
                Return Me.organizationNameField
            End Get
            Set(value As String)
                Me.organizationNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OrganizationLabel() As String
            Get
                Return Me.organizationLabelField
            End Get
            Set(value As String)
                Me.organizationLabelField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBody

        Private wsSetUpOrganizationStatusResponseField As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponse

        Private errorResponseField As EpcsResponseEpcsResponseBodyErrorResponse

        '''<remarks/>
        Public Property WsSetUpOrganizationStatusResponse() As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponse
            Get
                Return Me.wsSetUpOrganizationStatusResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponse)
                Me.wsSetUpOrganizationStatusResponseField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorResponse() As EpcsResponseEpcsResponseBodyErrorResponse
            Get
                Return Me.errorResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponse)
                Me.errorResponseField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponse

        Private organizationResponseField As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponse

        '''<remarks/>
        Public Property OrganizationResponse() As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponse
            Get
                Return Me.organizationResponseField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponse)
                Me.organizationResponseField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponse

        Private statusField As String

        Private errorField As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponseError

        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set(value As String)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Error]() As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponseError
            Get
                Return Me.errorField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponseError)
                Me.errorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyWsSetUpOrganizationStatusResponseOrganizationResponseError

        Private errorCodeField As String

        Private errorTextField As String

        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set(value As String)
                Me.errorCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorText() As String
            Get
                Return Me.errorTextField
            End Get
            Set(value As String)
                Me.errorTextField = Value
            End Set
        End Property
    End Class
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponse

        Private errorResponseListField As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList

        '''<remarks/>
        Public Property ErrorResponseList() As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList
            Get
                Return Me.errorResponseListField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList)
                Me.errorResponseListField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponseErrorResponseList

        Private errorField As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError

        '''<remarks/>
        Public Property [Error]() As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError
            Get
                Return Me.errorField
            End Get
            Set(value As EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError)
                Me.errorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="urn:drfirst.com:epcsapi:v1_0")> _
    Partial Public Class EpcsResponseEpcsResponseBodyErrorResponseErrorResponseListError

        Private errorCodeField As String

        Private errorTextField As String

        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set(value As String)
                Me.errorCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorText() As String
            Get
                Return Me.errorTextField
            End Get
            Set(value As String)
                Me.errorTextField = value
            End Set
        End Property
    End Class
End Namespace